### ISSUE TITLE
getqflist() returns 'type'. Why ignore it?

### ISSUE THREAD

**Issue by aecepoglu** [Palpatineli/lightline-lsc-nvim#1]
When inside a code file with a syntax error, I can get this:

`echo getqflist()`
```js
[{'lnum': 6, 'bufnr': 1, 'col': 2, 'valid': 1, 'vcol': 0, 'nr': 0, 'type': 'E', 'pattern': '', 'text': 'Error: Syntax e
rror'}]
```

I tried to have my language-server produce some warnings but none did, so I couldn't see any `type` that isn't `E`, but I assume there could be some and we could add support for warnings to this.

Right?

**Comment by Palpatineli** [comment]
I'll look into that. No promises though.

**Comment by aecepoglu** [comment]
If you like I can do it.

Is this solution OK?:

- [x] https://github.com/Palpatineli/lightline-lsc-nvim/blob/master/autoload/lightline/lsc.vim#L28 : `error_no` should be number of items whose `type` is `E`.
- [x] Similarly the `function! lightline#lsc#warnings()` method will be implemented.
- [x] `let s:indicator_warnings = get(g:, 'lightline#lsc#indicator_warnings', 'W:')`

**Comment by aecepoglu** [comment]
Have you had a chance to look at this yet?

**Comment by aecepoglu** [comment]
Well, since this issue has been ignored for over 2 years, I'm gonna close it.
